#!/usr/bin/env bash
# Pixel Reveal — installer. Sets up a Python virtualenv, installs dependencies,
# and seeds a .env file. Safe to re-run (idempotent).
set -euo pipefail
cd "$(dirname "$0")"

PORT="${PORT:-8777}"

say() { printf '· %s\n' "$1"; }
die() { printf 'error: %s\n' "$1" >&2; exit 1; }

# --- pick a Python toolchain: prefer uv (fast), fall back to venv + pip -------
if command -v uv >/dev/null 2>&1; then
  say "using uv"
  if [ ! -d .venv ]; then
    say "creating venv"
    uv venv
  fi
  say "installing dependencies"
  uv pip install -r requirements.txt
else
  command -v python3 >/dev/null 2>&1 || die "need either 'uv' or 'python3' on PATH"
  say "uv not found — using python3 venv + pip"
  if [ ! -d .venv ]; then
    say "creating venv"
    python3 -m venv .venv
  fi
  say "installing dependencies"
  .venv/bin/python -m pip install --upgrade pip >/dev/null
  .venv/bin/pip install -r requirements.txt
fi

# --- seed .env with a real SECRET_KEY (Google creds stay blank/optional) ------
if [ ! -f .env ]; then
  say "creating .env"
  SECRET_KEY="$(.venv/bin/python -c 'import secrets; print(secrets.token_hex(32))')"
  {
    echo "# Generated by install.sh. Fill GOOGLE_* to enable Google sign-in (optional)."
    echo "SECRET_KEY=${SECRET_KEY}"
    echo "GOOGLE_CLIENT_ID="
    echo "GOOGLE_CLIENT_SECRET="
  } > .env
else
  say ".env already exists — leaving it untouched"
fi

echo
say "done. start the server with:"
echo "    ./run.sh"
echo "  then open http://127.0.0.1:${PORT}"
